const ERROR_CODES = {
  // Authentication errors
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',

  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALIDATION_EMAIL_INVALID: 'VALIDATION_EMAIL_INVALID',
  VALIDATION_PASSWORD_WEAK: 'VALIDATION_PASSWORD_WEAK',
  VALIDATION_REQUIRED_FIELD: 'VALIDATION_REQUIRED_FIELD',

  // Resource errors
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',

  // Permission errors
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  PERMISSION_INSUFFICIENT: 'PERMISSION_INSUFFICIENT',

  // Business logic errors
  BUSINESS_MERCHANT_EXISTS: 'BUSINESS_MERCHANT_EXISTS',
  BUSINESS_ACCOUNT_SUSPENDED: 'BUSINESS_ACCOUNT_SUSPENDED',
  BUSINESS_INVALID_ROLE: 'BUSINESS_INVALID_ROLE',

  // Server errors
  SERVER_ERROR: 'SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
};

const ERROR_MESSAGES = {
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: 'Invalid email or password',
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: 'Token has expired',
  [ERROR_CODES.AUTH_TOKEN_INVALID]: 'Invalid token',
  [ERROR_CODES.AUTH_UNAUTHORIZED]: 'Authentication required',

  [ERROR_CODES.VALIDATION_ERROR]: 'Validation failed',
  [ERROR_CODES.VALIDATION_EMAIL_INVALID]: 'Invalid email format',
  [ERROR_CODES.VALIDATION_PASSWORD_WEAK]: 'Password is too weak',
  [ERROR_CODES.VALIDATION_REQUIRED_FIELD]: 'Required field is missing',

  [ERROR_CODES.RESOURCE_NOT_FOUND]: 'Resource not found',
  [ERROR_CODES.RESOURCE_ALREADY_EXISTS]: 'Resource already exists',
  [ERROR_CODES.RESOURCE_CONFLICT]: 'Resource conflict',

  [ERROR_CODES.PERMISSION_DENIED]: 'Permission denied',
  [ERROR_CODES.PERMISSION_INSUFFICIENT]: 'Insufficient permissions',

  [ERROR_CODES.BUSINESS_MERCHANT_EXISTS]: 'Merchant already exists',
  [ERROR_CODES.BUSINESS_ACCOUNT_SUSPENDED]: 'Account is suspended',
  [ERROR_CODES.BUSINESS_INVALID_ROLE]: 'Invalid role',

  [ERROR_CODES.SERVER_ERROR]: 'Internal server error',
  [ERROR_CODES.DATABASE_ERROR]: 'Database error',
  [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: 'External service error',
};

const getErrorMessage = (errorCode) => {
  return ERROR_MESSAGES[errorCode] || 'Unknown error';
};

module.exports = {
  ERROR_CODES,
  ERROR_MESSAGES,
  getErrorMessage,
};